language: python
python:
  - "2.7"
  - "3.6"
# command to run tests
before_script:
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - pytest .
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - linards.kalvans@gmail.com
