language: python
python:
- '2.7'
- '3.6'
before_script:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest .
after_success:
- coverage run --source=pynoaa pytest .
- coveralls
notifications:
  email:
    recipients:
    - linards.kalvans@gmail.com
env:
  global:
    secure: GMDzlBpxEsyZM+cQpeoOBveRaQd36I5e7VSINTHcNKkYWjgIrKjV6pc+DWtG8L0S826Bt7TlDjm/6BrEOJsGPVBtPS//DtMXAU74kDTb+qjrgZpl1sbhQTvHSmQ0XXfWcwC5Ac7bngzvx1ihJUcz0iwEQBayQ+Gby++7+c18VwdaGo6GYOf78JQHogzmjLoqQ56zpQ+Bh+fTz0SwbARP8cisnsLjuqtIrCcOd8OJ8ASH4TEB493kGNC7Yicz9nxABwGH49RfTv6vjIcT45EhJ/pHnQqPtUBmbNj+zqA500Gop0Xr1km3D0e28dRlEtkmCUIOktySJu25sd53Xy/WkYHH5JykjJDXOltEw73X6nJfoDZuxbZkrpzhGVBVwz0/NzS4v8bza2VNlnNEDLtnAsGwC0G3ix0OdYi5Nlou1AIcjgs6wAkNEEb7I3Dav2lfSVrwqKnrEjkrmMs/J/I6FvadQzV3EvcL9NthGWozs6cIRWTvJwH4UysSaIZ8+f27anNPnt7vrHXh0usYMb8UipTJQPOoyVCpfKbKowZU8FKcF+G3lq0r6isnXfCNkvDUG3gx5xydnAw9QfnB9d4lfzghocIV92FSD2d+iW+0zSqZd9/02x/0ZRk6wb80uqtkMR6eFihnmAaqtmAojct0TRHu/OUZ94aBZ4PqZ1qfneQ=
