language: python
python:
  - "2"
  - "3"
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
notifications:
  email:
    recipients:
      - linards.kalvans@gmail.com
