language: python
python:
  - "2.7"
  - "3.6"
# command to run tests
script:
  - pytest --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - linards.kalvans@gmail.com
